.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml, build.gradle
- sonarcloud 연동했습니다.
**
**
**
**
**
=> [BE] feat: sonarCloud 연동

src/main/java/com/h1/mycardeepdive/options/ui/dto/AdditionalOptionResponse.java, src/main/java/com/h1/mycardeepdive/options/ui/dto/BasicOptionResponse.java, src/main/java/com/h1/mycardeepdive/options/ui/dto/OptionCoordinatesResponse.java, src/main/java/com/h1/mycardeepdive/options/ui/dto/PackageOptionResponse.java
=> [BE] refactor: dto 필드 명시적으로 변경

frontend/src/App.tsx, frontend/src/Components/Loading/index.tsx, frontend/src/hooks/useFetch.ts, frontend/src/router/index.tsx
**
**
* 백엔드 API 호출을 위한 준비
* 라우터 분리
**
- useFetch 커스텀 훅
- Suspense 설정
- 라우터 분리
**
**
=> [FE] useFetch & Suspense

src/main/java/com/h1/mycardeepdive/options/mapper/OptionMapper.java, src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java, src/main/java/com/h1/mycardeepdive/options/ui/dto/PackageOptionResponse.java, src/test/java/com/h1/mycardeepdive/options/ui/OptionsControllerTest.java
패키지 옵션 제공 시 포함된 옵션들의 정보를 dto에 추가했습니다.
**
**
**
**
**
=> [BE] feat: 패키지 옵션에 포함된 옵션 리스트 dto에 추가

frontend/.github/workflows/deploy.yml
=> [FE] deploy V0.0.1

.github/workflows/deploy.yml
=> [FE] HOTFIX: fixed deploy.yml V0.0.1 

.github/workflows/deploy.yml
=> [FE] hotfix fixed deploy.yml V0.0.1

src/main/java/com/h1/mycardeepdive/car/domain/CarSpec.java, src/main/java/com/h1/mycardeepdive/color/domain/ColorCombination.java, src/main/java/com/h1/mycardeepdive/color/domain/ExteriorColor.java, src/main/java/com/h1/mycardeepdive/color/domain/InteriorColor.java, src/main/java/com/h1/mycardeepdive/color/domain/TrimColorCombination.java, src/main/java/com/h1/mycardeepdive/color/domain/TrimExteriorColor.java, src/main/java/com/h1/mycardeepdive/color/domain/TrimInteriorColor.java, src/main/java/com/h1/mycardeepdive/color/domain/repository/TrimExteriorColorRepository.java, src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java, src/main/java/com/h1/mycardeepdive/color/service/ColorService.java, src/main/java/com/h1/mycardeepdive/color/ui/ColorController.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/AllColorResponse.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java, src/main/resources/db/migration/V1__init.sql, src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java, src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java, src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java, src/test/java/com/h1/mycardeepdive/fixture/ExteriorColorFixture.java, src/test/java/com/h1/mycardeepdive/fixture/InteriorColorFixture.java
=> [BE] Color API 수정

src/main/resources/db/migration/V1__init.sql
=> [BE] fix: description varchar길이 65000에서 5000으로 수정

frontend/index.html, frontend/src/index.css, frontend/vite.config.ts
**
**
* 배포 환경에서 js, css 파일을 제대로 못 불러오는 문제 해결
**
**
**
=> [FE] 배포 환경에서 js, css 파일 못 찾는 문제 해결

src/main/java/com/h1/mycardeepdive/options/domain/CarSpecOptions.java, src/main/java/com/h1/mycardeepdive/options/domain/CarSpecPackage.java, src/main/resources/db/migration/V1__init.sql
- 컨벤션을 고려하여 테이블 명을 변경했습니다.
**
**
**
**
**
=> [BE] refactor: carspec 테이블명 car_spec으로 수정

src/main/resources/db/migration/V1_2__insert_data.sql
**
**
DB에 데이터를 삽입하는 쿼리를 작성했습니다
db서버의 /var/lib/mysql/mycar_db에 csv파일을 넣어두면 이 파일을 읽어 데이터를 삽입합니다.
**
**
**
=> [BE] db 데이터 삽입 쿼리 작성

src/main/resources/db/migration/V1_2__insert_data.sql
=> hotfix: db 삽입 쿼리 중 파일 경로 수정

src/main/resources/db/migration/V1_2__init_insert_data.sql
=> [BE] hotfix: db 삽입 쿼리 수정

src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java, src/main/java/com/h1/mycardeepdive/color/service/ColorService.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/AllColorResponse.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorInfo.java, src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java, src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
**
**
- 색상 조회 시 트림명이 필요함에 따라 트림명과 트림id를 추가로 반환 
- 모든 컬러 반환 시 변수 명이 카멜케이스로 되어있어 스네이크케이스로 수정
**
**
**
=> [BE] 색상 조회 api에 트림명 추가, 변수명 수정

src/main/resources/db/migration/V1_3__init_recommendation.sql
=> [BE] fix: 추천 관련 테이블 생성 sql 수정2

src/main/java/com/h1/mycardeepdive/car/domain/CarSpec.java, src/main/java/com/h1/mycardeepdive/color/domain/ExteriorColor.java, src/main/java/com/h1/mycardeepdive/color/domain/InteriorColor.java, src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java, src/main/java/com/h1/mycardeepdive/color/service/ColorService.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorInfo.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/ExteriorColorResponse.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorInfo.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/InteriorColorResponse.java, src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java, src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
**
**
- 색상 API 반환 형식 변경
**
**
**
=> [BE] feature/api recommendation custom

GetYa/GetYa.xcodeproj/project.pbxproj, GetYa/GetYa/Domain/Entity/AdditionalOption.swift, GetYa/GetYa/Domain/Entity/AdditionalOptionList.swift, GetYa/GetYa/Domain/Entity/AdditionalOptionPackage.swift, GetYa/GetYa/Domain/Entity/BasicOption.swift, GetYa/GetYa/Domain/Entity/OptionDetail.swift, GetYa/GetYa/Domain/Entity/PackageOptionDetail.swift, GetYa/GetYa/Domain/Entity/Tag.swift, GetYa/GetYa/Domain/Entity/TagDetail.swift, GetYa/GetYa/Domain/Entity/TagOption.swift, GetYa/GetYa/Domain/Entity/TrimOption.swift, GetYa/GetYa/Domain/Entity/TrimSubOption.swift, GetYa/GetYa/Presentation/CarSettingSelect/OptionSelect/OptionSelectItemCell.swift
**
**
**
- 8월 21일 22:30 분 기준 API에 나온 엔티티 모두 구현
**
**
=> [iOS] API 요청, 응답 시 필요한 엔티티 생성

src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java, src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java, src/main/java/com/h1/mycardeepdive/color/service/ColorService.java, src/main/java/com/h1/mycardeepdive/color/ui/ColorController.java, src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java, src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java, src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java, src/test/java/com/h1/mycardeepdive/color/service/ColorServiceTest.java, src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
**
**
- 트림 선택 시 트림id를 보냅니다.
- 컬러 선택 시 컬러id를 보냅니다.
**
**
**
=> [BE] feat: 트림, 컬러 선택 시 로그 전송 API구현

src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java, src/main/java/com/h1/mycardeepdive/car/ui/CarSpecController.java, src/test/java/com/h1/mycardeepdive/car/service/CarSpecServiceTest.java, src/test/java/com/h1/mycardeepdive/car/ui/CarSpecControllerTest.java
**
**
- 추천받은 사양에서 커스텀하기로 넘어갈 경우 카스펙id를 통해 같은 엔진, 바디, 구동방식을 가지는 트림들을 조회하는 API추가
**
**
**
=> [BE] feat: carSpecId로 같은 스펙인 carSpec들 조회 기능 구현

scripts-dev/pull-and-run-container-dev.sh, scripts-prod/pull-and-run-container-prod.sh, src/main/java/com/h1/mycardeepdive/car/mapper/CarSpecMapper.java, src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecInfo.java, src/main/java/com/h1/mycardeepdive/car/ui/dto/CarSpecResponse.java, src/main/java/com/h1/mycardeepdive/color/mapper/ColorMapper.java, src/main/java/com/h1/mycardeepdive/color/ui/dto/ColorInfo.java
**
**
- 트림 조회 시 컬러 아이콘 이미지 추가로 반환
- 컬러 조회 시 내장색상에서 사용가능한 외장색상id, 외장색상에서 사용가능한 내장색상 id 추가로 반환
**
**
**
=> [BE] feat: 트림, 컬러 반환 API 수정

build.gradle, src/main/java/com/h1/mycardeepdive/global/scheduler/LogCleanupScheduler.java, src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java, src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationOptionInfo.java, src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java, src/main/resources/logback-spring.xml, src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
**
**
- 로그를 로그스태시 encoder를 사용하여 json형식으로 로그파일에 저장
- local, dev, prod프로파일별 다른 로그레벨과 appender적용
- 로그를 월요일 자정에 삭제하도록 설정
**
**
**
=> [BE] feat: 로그를 파일로 저장

src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java, src/main/java/com/h1/mycardeepdive/color/service/ColorService.java, src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java, src/main/resources/logback-spring.xml, src/test/java/com/h1/mycardeepdive/color/ui/ColorControllerTest.java
**
**
- 로그 출력 형식 수정
- activity-log 요청에 로그 출력
- 
**
**
**
=> [BE] feat: activity-log요청에 로그 출력

GetYa/GetYa/Util/Protocol/Requestable.swift, GetYa/GetYa/Util/Service/Endpoint.swift, GetYa/GetYa/Util/Service/SessionProvider.swift
- bodyParam 추가.
- httpMethod = .post로 해야합니다 !!
=> [iOS] network endpoint bodyParam 추가했습니다.

src/main/java/com/h1/mycardeepdive/recommendation/domain/Recommendation.java, src/main/java/com/h1/mycardeepdive/recommendation/domain/RecommendationCar.java, src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java, src/main/java/com/h1/mycardeepdive/recommendation/service/RecommendationService.java, src/main/java/com/h1/mycardeepdive/recommendation/ui/dto/RecommendationResponse.java, src/main/resources/db/migration/V1_3__init_recommendation.sql, src/main/resources/db/migration/V1_5__init_insert_recommendation_data.sql, src/main/resources/db/migration/V1_6__init_delete_wrong_data.sql, src/test/java/com/h1/mycardeepdive/fixture/CustomRecommendationFixture.java, src/test/java/com/h1/mycardeepdive/fixture/RecommendationFixture.java, src/test/java/com/h1/mycardeepdive/recommendation/service/RecommendationServiceTest.java
**
**
- 추천응답 dto수정
- db마이그레이션 sql수정
**
**
**
=> [BE] deploy v0.1.1

frontend/src/api/Recommendation/getCustomRecommendation.tsx, frontend/src/api/Recommendation/getRecommendation.tsx, frontend/src/api/color/getAllColor.tsx, frontend/src/api/color/getExteriorColor.tsx, frontend/src/api/myCar/getMyCarResult.tsx, frontend/src/api/myCar/postResult.tsx, frontend/src/api/option/getAdditionalOptions.tsx, frontend/src/api/option/getBasicOptions.tsx, frontend/src/api/option/getOptionDetails.tsx, frontend/src/api/option/getPackageOptionDetails.tsx, frontend/src/api/option/getSituationOptions.tsx, frontend/src/api/trim/getComparison.tsx, frontend/src/api/trim/getTrim.tsx, frontend/src/hooks/useFetch.ts
**
**
* useTransition 해제했습니다.
**
**
**
=> [FE] 최적화 수정

frontend/src/Components/CarRotation/index.tsx, frontend/src/Pages/OptionSelectitonPage/BasicOption/index.tsx, frontend/src/Pages/OptionSelectitonPage/index.tsx, frontend/src/api/option/getBasicOptions.tsx, frontend/src/hooks/useFetch.ts, frontend/src/hooks/useLogFetch.ts
**
**
**
* 로그 API 콘솔 지웠습니다.
* 기본 옵션 타입 수정했습니다.
**
**
=> [FE] 로그 API, 기본 옵션 수정

frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx, frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
=> [FE] 느낌표 크기 줄이기

src/main/java/com/h1/mycardeepdive/color/service/ColorService.java
**
**
- 트림id로 모든 컬러 조회 시 내장, 외장 매치 안되는 것 수정
**
**
**
=> [BE] fix: 트림id로 모든 컬러 조회 시 내장, 외장 매치 안되는 것 수정

src/main/java/com/h1/mycardeepdive/car/service/CarSpecService.java, src/main/java/com/h1/mycardeepdive/color/service/ColorService.java, src/main/java/com/h1/mycardeepdive/options/service/OptionsService.java, src/main/java/com/h1/mycardeepdive/pdf/service/MailService.java, src/main/java/com/h1/mycardeepdive/pdf/service/MailServiceImpl.java, src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java, src/main/java/com/h1/mycardeepdive/pdf/service/S3Service.java, src/main/java/com/h1/mycardeepdive/pdf/ui/PdfController.java, src/test/java/com/h1/mycardeepdive/pdf/service/MailServiceImplTest.java, src/test/java/com/h1/mycardeepdive/pdf/ui/PdfControllerTest.java
- 3가지 작업을 수행하는 함수를 1가지 일을 하는 3개의 함수로 분리
- 자바 상수로 관리
- reflection을 통한 private 메서드 테스트
**
**
- mail
- 3가지 작업을 수행하는 함수를 1가지 일을 하는 3개의 함수로 분리
- sendMessage, renderMailHtml, createEmailDomain
- PDFService, OptionService, ColorService
- 자바 상수로 관리
- test
- reflection을 통한 private renderMailHtml, createEmailDomain 테스트
**
**
**
=> [BE] refactor: PDF/메일 도메인 리팩토링

frontend/src/Pages/ColorSelectionPage/ColorItems/Icon/index.tsx, frontend/src/Pages/ColorSelectionPage/ColorItems/Image/index.tsx, frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx, frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx, frontend/src/Pages/ColorSelectionPage/index.tsx
**
#
**
- 호환 불가능한 색 느낌표 위치 옮기기
**
**
**
=> [FE] 호환 불가능한 색 느낌표 위치 옮기기

frontend/src/Components/Header/showQuotation/index.tsx, frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx, frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/SelectedButton/index.tsx, frontend/src/Pages/OptionSelectitonPage/AdditionalOption/Option/UnSelectedButton/index.tsx, frontend/src/Pages/RecommendationPage/ResultPage/Buttons/index.tsx, frontend/src/Pages/TrimSelectionPage/Trim/ChangeModal/Buttons/index.tsx, frontend/src/context/CarProvider/index.tsx, frontend/src/context/CarProvider/type.ts
**
**
-  추천 받고 커스텀 누르면 색상 쪽에 채택률 안뜨는 현상
-  다른 트림으로 바뀌면 색상과 옵션 해제
-  다른 색상으로 바뀌면 옵션 해제
-  견적내기 누르면 5.1로 이동
**
**
**
=> [FE] 버그와 빠진 내용 수정

frontend/src/Pages/ColorSelectionPage/ChangerModal/Explain/index.tsx, frontend/src/Pages/ColorSelectionPage/ChangerModal/Title/index.tsx, frontend/src/Pages/ColorSelectionPage/ChangerModal/index.tsx, frontend/src/Pages/ColorSelectionPage/ExteriorDropDown/index.tsx, frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorDropDown/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx, frontend/src/Pages/ColorSelectionPage/UnavailableChangerModal/index.tsx
**
**
**
- 호환 불가능 색상 클릭시 모달 띄우기
**
**
=> [FE] 호환 불가능 색상 선택시 모달 띄우기

frontend/src/Components/Toast/index.tsx
**
**
* 토스트 애니메이션 수정했어요!
**
**
**
=> [FE] 토스트 애니메이션 수정

frontend/src/Components/CarRotation/index.tsx
**
**
- 차량 이미지 undefined 버그 수정
**
**
**
=> [FE] 차량 이미지 버그 수정

frontend/src/Pages/ColorSelectionPage/ExteriorItems/index.tsx, frontend/src/Pages/ColorSelectionPage/InteriorItems/index.tsx
**
**
**
- 내장 클릭 시 내장 이미지 띄우기
**
**
=> [FE] 내장 클릭 시 내장 이미지 띄우기

GetYa/GetYa/Presentation/Common/View/CommonOptionView.swift
**
**
**
- QuotateFinishVIewController 옵션 가격 내용 표현 수정
**
**
=> [iOS] QuotateFinishVIewController 옵션 가격 내용 표현 수정

frontend/src/Components/Toast/index.tsx, frontend/src/Pages/TrimSelectionPage/Trim/CompareModal/Trim/BasicOption/BasicOptionItem/index.tsx, frontend/src/Pages/TrimSelectionPage/Trim/CompareModal/Trim/BasicOption/index.tsx, frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
**
**
- 트림 선택 버튼 사이 라인
- 콘솔 로그 제거
- 내장 색상 에러
- 추천 결과 에러
**
**
**
=> [FE] 약간의 버그들

src/main/resources/application.yml, src/main/resources/templates/template.html
- db에 batch 테이블 생성되게 설정 변경했습니다.
**
**
**
**
**
=> [BE] hotfix: initialize-schema: always 추가

src/main/java/com/h1/mycardeepdive/recommendation/mapper/RecommendationMapper.java
**
**
- 추천 견적에서 패키지 옵션 처리에 문제가 있어 추천 패키지를 반환하지 않도록 수정
**
**
**
=> [BE] fix: 추천에서 패키지 반환하지 않게 수정

frontend/src/context/CacheProvider/index.tsx
**
**
- 캐싱 시간 5분으로 변경했습니다.
**
**
**
=> [FE] 데이터 캐싱 시간 변경

src/main/java/com/h1/mycardeepdive/pdf/service/PdfService.java
- 내장, 외장 색상 가격을 총 가격에 반영했습니다.
**
**
**
**
**
=> [BE] fix: 내장, 외장 가격 색상 총 가격에 반영

frontend/src/Pages/TrimSelectionPage/Trim/TrimRadio/index.tsx
**
**
- 트림 라디오 버튼 key 수정했습니다
**
**
**
=> [FE] 트림 라디오 키 수정

frontend/src/Pages/TrimSelectionPage/Feature/InformationModal/index.tsx
**
**
- 정보 팝업에서 가로로 스크롤되는 버그 수정
**
**
**
=> [FE] 스크롤 버그

README.md
=> [FE] get main readme.md
